export interface MarketConfig {
    id: string;
    country: string;
    countryCode: string;
    city: string;
    currency: string;
    locale: string;
    timezone: string;
    paymentProcessor: 'stripe' | 'local';
    stripeAccountId?: string;
    taxRate: number;
    taxName: string;
    regulatoryNotes?: string;
}

export const MARKETS: Record<string, MarketConfig> = {
    'milan-italy': {
        id: 'milan-italy',
        country: 'Italy',
        countryCode: 'IT',
        city: 'Milan',
        currency: 'EUR',
        locale: 'it-IT',
        timezone: 'Europe/Rome',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_IT,
        taxRate: 0.22,
        taxName: 'IVA',
        regulatoryNotes: 'EU GDPR compliant. VAT registered businesses required.',
    },
    'rome-italy': {
        id: 'rome-italy',
        country: 'Italy',
        countryCode: 'IT',
        city: 'Rome',
        currency: 'EUR',
        locale: 'it-IT',
        timezone: 'Europe/Rome',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_IT,
        taxRate: 0.22,
        taxName: 'IVA',
        regulatoryNotes: 'EU GDPR compliant. VAT registered businesses required.',
    },
    'new-york-usa': {
        id: 'new-york-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'New York',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/New_York',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.08875,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    'london-uk': {
        id: 'london-uk',
        country: 'United Kingdom',
        countryCode: 'GB',
        city: 'London',
        currency: 'GBP',
        locale: 'en-GB',
        timezone: 'Europe/London',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_GB,
        taxRate: 0.20,
        taxName: 'VAT',
        regulatoryNotes: 'UK GDPR compliant. VAT registration threshold applies.',
    },
    'berlin-germany': {
        id: 'berlin-germany',
        country: 'Germany',
        countryCode: 'DE',
        city: 'Berlin',
        currency: 'EUR',
        locale: 'de-DE',
        timezone: 'Europe/Berlin',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_DE,
        taxRate: 0.19,
        taxName: 'MwSt',
        regulatoryNotes: 'EU GDPR compliant. German tax law applies.',
    },
    'melbourne-australia': {
        id: 'melbourne-australia',
        country: 'Australia',
        countryCode: 'AU',
        city: 'Melbourne',
        currency: 'AUD',
        locale: 'en-AU',
        timezone: 'Australia/Melbourne',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_AU,
        taxRate: 0.10,
        taxName: 'GST',
        regulatoryNotes: 'Australian Consumer Law applies. GST registered businesses required.',
    },
    'sydney-australia': {
        id: 'sydney-australia',
        country: 'Australia',
        countryCode: 'AU',
        city: 'Sydney',
        currency: 'AUD',
        locale: 'en-AU',
        timezone: 'Australia/Sydney',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_AU,
        taxRate: 0.10,
        taxName: 'GST',
        regulatoryNotes: 'Australian Consumer Law applies. GST registered businesses required.',
    },
    'toronto-canada': {
        id: 'toronto-canada',
        country: 'Canada',
        countryCode: 'CA',
        city: 'Toronto',
        currency: 'CAD',
        locale: 'en-CA',
        timezone: 'America/Toronto',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_CA,
        taxRate: 0.13,
        taxName: 'HST',
        regulatoryNotes: 'Canadian privacy laws apply. HST registered businesses required.',
    },
    'paris-france': {
        id: 'paris-france',
        country: 'France',
        countryCode: 'FR',
        city: 'Paris',
        currency: 'EUR',
        locale: 'fr-FR',
        timezone: 'Europe/Paris',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_FR,
        taxRate: 0.20,
        taxName: 'TVA',
        regulatoryNotes: 'EU GDPR compliant. French tax law applies.',
    },
    'madrid-spain': {
        id: 'madrid-spain',
        country: 'Spain',
        countryCode: 'ES',
        city: 'Madrid',
        currency: 'EUR',
        locale: 'es-ES',
        timezone: 'Europe/Madrid',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_ES,
        taxRate: 0.21,
        taxName: 'IVA',
        regulatoryNotes: 'EU GDPR compliant. Spanish tax law applies.',
    },
    'barcelona-spain': {
        id: 'barcelona-spain',
        country: 'Spain',
        countryCode: 'ES',
        city: 'Barcelona',
        currency: 'EUR',
        locale: 'es-ES',
        timezone: 'Europe/Madrid',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_ES,
        taxRate: 0.21,
        taxName: 'IVA',
        regulatoryNotes: 'EU GDPR compliant. Spanish tax law applies.',
    },
    // More US Cities
    'los-angeles-usa': {
        id: 'los-angeles-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'Los Angeles',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/Los_Angeles',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.0975,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    'chicago-usa': {
        id: 'chicago-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'Chicago',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/Chicago',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.1025,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    'san-francisco-usa': {
        id: 'san-francisco-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'San Francisco',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/Los_Angeles',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.0875,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    'boston-usa': {
        id: 'boston-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'Boston',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/New_York',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.0625,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    'seattle-usa': {
        id: 'seattle-usa',
        country: 'United States',
        countryCode: 'US',
        city: 'Seattle',
        currency: 'USD',
        locale: 'en-US',
        timezone: 'America/Los_Angeles',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_US,
        taxRate: 0.101,
        taxName: 'Sales Tax',
        regulatoryNotes: 'State and local tax compliance required.',
    },
    // Asia-Pacific
    'tokyo-japan': {
        id: 'tokyo-japan',
        country: 'Japan',
        countryCode: 'JP',
        city: 'Tokyo',
        currency: 'JPY',
        locale: 'ja-JP',
        timezone: 'Asia/Tokyo',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_JP,
        taxRate: 0.10,
        taxName: 'Consumption Tax',
        regulatoryNotes: 'Japanese tax law applies.',
    },
    'singapore-singapore': {
        id: 'singapore-singapore',
        country: 'Singapore',
        countryCode: 'SG',
        city: 'Singapore',
        currency: 'SGD',
        locale: 'en-SG',
        timezone: 'Asia/Singapore',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_SG,
        taxRate: 0.08,
        taxName: 'GST',
        regulatoryNotes: 'Singapore tax law applies.',
    },
    'hong-kong-china': {
        id: 'hong-kong-china',
        country: 'Hong Kong',
        countryCode: 'HK',
        city: 'Hong Kong',
        currency: 'HKD',
        locale: 'en-HK',
        timezone: 'Asia/Hong_Kong',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_HK,
        taxRate: 0.00,
        taxName: 'No VAT',
        regulatoryNotes: 'Hong Kong tax law applies.',
    },
    'mumbai-india': {
        id: 'mumbai-india',
        country: 'India',
        countryCode: 'IN',
        city: 'Mumbai',
        currency: 'INR',
        locale: 'en-IN',
        timezone: 'Asia/Kolkata',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_IN,
        taxRate: 0.18,
        taxName: 'GST',
        regulatoryNotes: 'Indian tax law applies.',
    },
    // Latin America
    'mexico-city-mexico': {
        id: 'mexico-city-mexico',
        country: 'Mexico',
        countryCode: 'MX',
        city: 'Mexico City',
        currency: 'MXN',
        locale: 'es-MX',
        timezone: 'America/Mexico_City',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_MX,
        taxRate: 0.16,
        taxName: 'IVA',
        regulatoryNotes: 'Mexican tax law applies.',
    },
    'buenos-aires-argentina': {
        id: 'buenos-aires-argentina',
        country: 'Argentina',
        countryCode: 'AR',
        city: 'Buenos Aires',
        currency: 'ARS',
        locale: 'es-AR',
        timezone: 'America/Argentina/Buenos_Aires',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_AR,
        taxRate: 0.21,
        taxName: 'IVA',
        regulatoryNotes: 'Argentine tax law applies.',
    },
    'sao-paulo-brazil': {
        id: 'sao-paulo-brazil',
        country: 'Brazil',
        countryCode: 'BR',
        city: 'São Paulo',
        currency: 'BRL',
        locale: 'pt-BR',
        timezone: 'America/Sao_Paulo',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_BR,
        taxRate: 0.18,
        taxName: 'ICMS',
        regulatoryNotes: 'Brazilian tax law applies.',
    },
    // More Europe
    'amsterdam-netherlands': {
        id: 'amsterdam-netherlands',
        country: 'Netherlands',
        countryCode: 'NL',
        city: 'Amsterdam',
        currency: 'EUR',
        locale: 'nl-NL',
        timezone: 'Europe/Amsterdam',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_NL,
        taxRate: 0.21,
        taxName: 'BTW',
        regulatoryNotes: 'EU GDPR compliant. Dutch tax law applies.',
    },
    'dublin-ireland': {
        id: 'dublin-ireland',
        country: 'Ireland',
        countryCode: 'IE',
        city: 'Dublin',
        currency: 'EUR',
        locale: 'en-IE',
        timezone: 'Europe/Dublin',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_IE,
        taxRate: 0.23,
        taxName: 'VAT',
        regulatoryNotes: 'EU GDPR compliant. Irish tax law applies.',
    },
    'stockholm-sweden': {
        id: 'stockholm-sweden',
        country: 'Sweden',
        countryCode: 'SE',
        city: 'Stockholm',
        currency: 'SEK',
        locale: 'sv-SE',
        timezone: 'Europe/Stockholm',
        paymentProcessor: 'stripe',
        stripeAccountId: process.env.STRIPE_ACCOUNT_SE,
        taxRate: 0.25,
        taxName: 'Moms',
        regulatoryNotes: 'EU GDPR compliant. Swedish tax law applies.',
    },
};

export const COUNTRIES = [
    { code: 'IT', name: 'Italy', flag: '🇮🇹' },
    { code: 'US', name: 'United States', flag: '🇺🇸' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦' },
    { code: 'FR', name: 'France', flag: '🇫🇷' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
    { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
    { code: 'IN', name: 'India', flag: '🇮🇳' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
];

export function getMarketsByCountry(countryCode: string): MarketConfig[] {
    return Object.values(MARKETS).filter(m => m.countryCode === countryCode);
}

export function getMarketById(id: string): MarketConfig | undefined {
    return MARKETS[id];
}

// No default market - user must select one
export const DEFAULT_MARKET = null;
